services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  workder:
    build: .
    volumes:
      - ./src:/app
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
  
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./src:/app
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports:
      - "8080:8080"